# Site settings
title:       Zp Bappi
email:       zpbappi@gmail.com
author:      Zp Bappi
description: my technology blog
baseurl:     ""
url:         "https://zpbappi.com"
timezone:    "Australia/Sydney"
date_format: "%b %-d, %Y"

# Google services
google_analytics: 
# UA-51923354-1
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: 
# UA-51923354-1
google_tag_manager: G-VTDRPKZTP2
# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

# Custom developed features
show_tags:            true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: #zpbappi

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: zpbappi
bitbucket_username:
stackoverflow_id:
twitter_username: zpbappi
google_plus_id: +ZpBappi
linkedin_username: zpbappi
skype_username:
steam_nickname:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'

# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# Default front matter settings
defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
kramdown:
  input: GFM
  hard_wrap: false
#redcarpet:
#  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true

highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
