# Site settings
title:       Zp Bappi
email:       zpbappi@gmail.com
author:      Zp Bappi
description: my technology blog
baseurl:     ""
url:         "http://zpbappi.github.io"
timezone:    "Australia/Sydney"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: false

# Custom developed features
show_tags:            true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: zpbappi
bitbucket_username:
stackoverflow_id:
twitter_username: zpbappi
google_plus_id: +ZpBappi
linkedin_username: zpbappi
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# Default front matter settings
defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

# Build settings
markdown:     kramdown
#redcarpet:
#  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
